[project]
name = "ufg"
version = "0.1.0"
description = "Validador de URL com Guardrails-AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.56.2",
    "python-dotenv>=1.0.1",
]
